barcodes: "BC01 BC02 BC03 BC04 BC05 BC06 BC07 BC08 BC09 BC10 BC11 BC12"
runs: "april"
min_read_length: 1000
keep_percent: 95
mean_q_weight: 10
check_reads: 100000
extra_end_trim: 10
porechop_out_format: "fastq.gz"
plot_downsample: 50000
container: "shub://mbhall88/Singularity_recipes:puntseq"
